version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/etc/nginx/logs:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - nginx-ctfd
      - nginx-wasmcloud
    restart: always

  # === ctfd ===
  ctfd-web:
    image: ctfd/ctfd:3.4.0
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@ctfd-db/ctfd
      - REDIS_URL=redis://ctfd-cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - ./ctfd-data/logs:/var/log/CTFd
      - ./ctfd-data/uploads:/var/uploads
    networks:
      # ctfd needs to be able to send smtp
      - default
      - nginx-ctfd
      - ctfd-internal
    depends_on:
      - ctfd-db
      - ctfd-cache

  ctfd-db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./ctfd-data/mysql:/var/lib/mysql
    networks:
      - ctfd-internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  ctfd-cache:
    image: redis:4
    restart: always
    volumes:
      - ./ctfd-data/redis:/data
    networks:
      - ctfd-internal

  # === chals ===
  whogdb:
    build: ../gdbchal
    ports:
      - 8001:1234
    restart: always
    networks:
      - default
  pow_erful:
    build: ../pow_erful
    ports:
      - 8002:1337
    env_file:
      - ../pow_erful/flag.env
    restart: always
    networks:
      - default
  wasmcloud:
    build: ../wasmcloud
    restart: always
    networks:
      # allow exfiltration
      - default
      - nginx-wasmcloud
    privileged: true

# isolate all web chal networks
networks:
  default:
  nginx-ctfd:
    internal: true
  nginx-wasmcloud:
    internal: true
  ctfd-internal:
    internal: true
